services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: insurance-ai-postgres

    environment:
      POSTGRES_DB: insurance_ai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d insurance_ai"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  postgres_data: