"""add message sources

Revision ID: 5785cd2a0d4e
Revises: 89da13b45f90
Create Date: 2026-09-07 20:26:42.300691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5785cd2a0d4e'
down_revision: Union[str, Sequence[str], None] = '89da13b45f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('document_chunk_id', sa.Uuid(), nullable=True),
    sa.Column('policy_coverage_id', sa.Uuid(), nullable=True),
    sa.Column('policy_option_id', sa.Uuid(), nullable=True),
    sa.Column('relevance_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_chunk_id'], ['document_chunks.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['policy_coverage_id'], ['policy_coverages.id'], ),
    sa.ForeignKeyConstraint(['policy_option_id'], ['policy_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_sources')
    # ### end Alembic commands ###
