"""add travel policy details

Revision ID: 6134f489d023
Revises: e5335cce0f3f
Create Date: 2026-09-04 19:56:17.787639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6134f489d023'
down_revision: Union[str, Sequence[str], None] = 'e5335cce0f3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_policy_details',
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('coverage_mode', sa.Enum('SINGLE_TRIP', 'ANNUAL_REPEATED', 'ANNUAL_LONG_TERM', name='coverage_mode'), nullable=False),
    sa.Column('territory', sa.Enum('DOMESTIC', 'EUROPE', 'WORLD', name='territory_type'), nullable=False),
    sa.Column('destination_country_code', sa.String(length=2), nullable=True),
    sa.Column('trip_purpose', sa.Enum('LEISURE', 'WORK_NON_MANUAL', 'WORK_MANUAL', name='trip_purpose'), nullable=True),
    sa.Column('sport_level', sa.Enum('RECREATIONAL', 'WINTER', 'RISKY', name='sport_level'), nullable=True),
    sa.Column('max_single_trip_days', sa.Integer(), nullable=True),
    sa.Column('departure_date', sa.Date(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('policy_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('travel_policy_details')
    # ### end Alembic commands ###
