"""add document chunks

Revision ID: a87c0e7e5756
Revises: 7084da2d53cd
Create Date: 2026-09-07 19:09:30.844220

"""
from typing import Sequence, Union

import pgvector

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a87c0e7e5756'
down_revision: Union[str, Sequence[str], None] = '7084da2d53cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable pgvector in PostgreSQL
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "document_chunks",

        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),

        sa.Column(
            "document_id",
            sa.Uuid(),
            nullable=False,
        ),

        sa.Column(
            "chunk_index",
            sa.Integer(),
            nullable=False,
        ),

        sa.Column(
            "page_number",
            sa.Integer(),
            nullable=True,
        ),

        sa.Column(
            "article_number",
            sa.String(length=100),
            nullable=True,
        ),

        sa.Column(
            "section_title",
            sa.String(length=255),
            nullable=True,
        ),

        sa.Column(
            "section_path",
            sa.String(length=500),
            nullable=True,
        ),

        sa.Column(
            "coverage_code",
            sa.String(length=100),
            nullable=True,
        ),

        sa.Column(
            "content",
            sa.Text(),
            nullable=False,
        ),

        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(),
            nullable=True,
        ),

        sa.Column(
            "metadata",
            postgresql.JSONB(
                astext_type=sa.Text()
            ),
            nullable=True,
        ),

        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
        ),

        sa.ForeignKeyConstraint(
            ["document_id"],
            ["knowledge_documents.id"],
        ),

        sa.PrimaryKeyConstraint("id"),

        sa.UniqueConstraint(
            "document_id",
            "chunk_index",
            name="uq_document_chunks_document_index",
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
