"""remove unique constraint from policy person

Revision ID: b3bca2bae4e0
Revises: dd1ab3d87383
Create Date: 2026-09-05 12:34:50.845811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3bca2bae4e0'
down_revision: Union[str, Sequence[str], None] = 'dd1ab3d87383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('policy_persons_person_id_key'), 'policy_persons', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('policy_persons_person_id_key'), 'policy_persons', ['person_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
