"""make policy person optional in policy coverage

Revision ID: c93119aa19bf
Revises: ec8864d00d4d
Create Date: 2026-09-06 17:52:13.911399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c93119aa19bf'
down_revision: Union[str, Sequence[str], None] = 'ec8864d00d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('policy_coverages', 'policy_person_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('policy_coverages', 'policy_person_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
