"""add policy coverages

Revision ID: ec8864d00d4d
Revises: f7ce7db2a460
Create Date: 2026-09-06 17:15:47.335361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec8864d00d4d'
down_revision: Union[str, Sequence[str], None] = 'f7ce7db2a460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_coverages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('coverage_type_id', sa.Uuid(), nullable=False),
    sa.Column('policy_person_id', sa.Uuid(), nullable=False),
    sa.Column('source_plan_coverage_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('limit_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('coverage_level', sa.String(length=100), nullable=True),
    sa.Column('deductible_type', sa.String(length=100), nullable=True),
    sa.Column('deductible_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coverage_type_id'], ['coverage_types.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['policy_person_id'], ['policy_persons.id'], ),
    sa.ForeignKeyConstraint(['source_plan_coverage_id'], ['plan_coverages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('uq_plans_product_versi    on_code'), 'plans', type_='unique')
    op.create_unique_constraint('uq_plans_product_version_code', 'plans', ['product_version_id', 'code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_plans_product_version_code', 'plans', type_='unique')
    op.create_unique_constraint(op.f('uq_plans_product_versi    on_code'), 'plans', ['product_version_id', 'code'], postgresql_nulls_not_distinct=False)
    op.drop_table('policy_coverages')
    # ### end Alembic commands ###
