"""add plan coverages

Revision ID: f7ce7db2a460
Revises: 31571076c48f
Create Date: 2026-09-06 14:54:22.915816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7ce7db2a460'
down_revision: Union[str, Sequence[str], None] = '31571076c48f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_coverages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('coverage_type_id', sa.Uuid(), nullable=False),
    sa.Column('included', sa.Boolean(), nullable=False),
    sa.Column('limit_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('coverage_level', sa.String(length=100), nullable=True),
    sa.Column('deductible_type', sa.String(length=100), nullable=True),
    sa.Column('deductible_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coverage_type_id'], ['coverage_types.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'coverage_type_id', name='uq_plan_coverages_plan_coverage_type')
    )
    op.drop_constraint(op.f('uq_plans_product_version_code'), 'plans', type_='unique')
    op.create_unique_constraint('uq_plans_product_versi    on_code', 'plans', ['product_version_id', 'code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_coverages')
    # ### end Alembic commands ###
